#!/usr/bin/env bash

# Ensure that the common script exists and is readable, then verify it has no
# syntax errors and defines the required function.
common_script="$(dirname "$0")/common.sh"
[ -r "$common_script" ] || { echo "[!] '$common_script' not found or not readable." >&2; exit 1; }
bash -n "$common_script" >/dev/null 2>&1 || { echo "[!] '$common_script' contains syntax errors." >&2; exit 1; }
source "$common_script"
declare -F set_colors >/dev/null 2>&1 || { echo "[!] '$common_script' does not define the required function." >&2; exit 1; }

set_colors

TOTAL_STEPS=5
CURRENT_STEP=0

# 1. Validate the workspace
((CURRENT_STEP++))
progress "$CURRENT_STEP" "$TOTAL_STEPS"

if ! test -d .git; then
    echo "Execute scripts/install-git-hooks in the top-level directory."
    exit 1
fi

ACCOUNT=$(git config --get remote.origin.url | awk -F'[:/]' '{print $(NF-1)}')
REPO_NAME=$(git config --get remote.origin.url | awk -F'[:/]' '{gsub(/\.git$/, "", $NF); print $NF}')

CURL=$(which curl)
if [ $? -ne 0 ]; then
  throw "curl not installed."
fi

CURL_RES=$(${CURL} -s \
-H "Accept: application/vnd.github.v3+json" \
https://api.github.com/repos/${ACCOUNT}/lab0-c/actions/workflows)

TOTAL_COUNT=$(echo ${CURL_RES} | sed -e 's/.*"total_count": \([^,"]*\).*/\1/')
case ${TOTAL_COUNT} in
    *"Not Found"*)
        echo "Check your repository. It should be located at https://github.com/${ACCOUNT}/lab0-c"
        exit 1
esac

if [[ "${ACCOUNT}" != "sysprog21" ]]; then
    REPO_FORKED=$(${CURL} -s \
    -H "Accept: application/vnd.github.v3+json" \
    https://api.github.com/repos/${ACCOUNT}/lab0-c | grep -m 1 fork)
    case ${REPO_FORKED} in
        *true*)
            ;;
        *)
            echo "Your repository MUST be forked from sysprog21/lab0-c"
            exit 1
    esac
fi

if [ ${TOTAL_COUNT} -eq "0" ]; then
    echo "Fatal: GitHub Actions MUST be activated."
    case ${OSTYPE} in
        "linux"*)
            xdg-open https://github.com/${ACCOUNT}/lab0-c/actions > /dev/null 2>&1
            ;;
        "darwin"*)
            open https://github.com/${ACCOUNT}/lab0-c/actions
            ;;
        *)
            echo "Please activate at https://github.com/${ACCOUNT}/lab0-c/actions"
            ;;
    esac
    echo "Check this article: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow"
    echo "Then, execute 'make' again."
    exit 1
else
    echo "GitHub Actions has been activated"
fi

mkdir -p .git/hooks

ln -sf ../../scripts/pre-commit.hook .git/hooks/pre-commit || exit 1
chmod +x .git/hooks/pre-commit

ln -sf ../../scripts/commit-msg.hook .git/hooks/commit-msg || exit 1
chmod +x .git/hooks/commit-msg

ln -sf ../../scripts/pre-push.hook .git/hooks/pre-push || exit 1
chmod +x .git/hooks/pre-push

ln -sf ../../scripts/prepare-commit-msg.hook .git/hooks/prepare-commit-msg || exit 1
chmod +x .git/hooks/prepare-commit-msg

touch .git/hooks/applied || exit 1

echo
echo "Git hooks are installed successfully."
